apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 20
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: brunosantos88/awsfrontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80      
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
    k8s-app: frontend
  name: frontend
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
  selector:
    app: frontend